### ISSUE TITLE
How can I access class in typecast method?

### ISSUE THREAD

**Issue by ljuba-roofr** [cycle/docs#172]
I'm looking at docs for [Column wrappers and typecast](https://cycle-orm.dev/docs/advanced-column-wrappers/current/en) and  `User` and `Uuid` example and I see that `castValue` method has 2 arguments

```php
public static function castValue(string $value, DatabaseInterface $db): static
```

Is there a way to access `User`  properties inside `Uuid->castValue` method? For example, can I get user `id` inside the `castValue`?

**Comment by roxblnfk** [comment]
Pay attention to [typecast handlers](https://cycle-orm.dev/docs/advanced-typecasting/current/en)
There you may handle all entity fields in one method

**Comment by ljuba-roofr** [comment]
Great. Thanks for the help!
