### ISSUE TITLE
Improve annotations codestyle using UpperCamelCase instead of lowerCamelCase

### ISSUE THREAD

**Issue by SerafimArts** [cycle/docs#30]
Suggests:
1) `@Entity` instead of `@entity`
2) `@Column` instead of `@column`
3) `@Embeddable` instead of `@embeddable`
4) `@HasOne` instead of `@hasOne`
5) `@HasMany` instead of `@hasMany`
6) `@BelongsTo` instead of `@belongsTo`
7) `@RefersTo` instead of `@refersTo`
8) `@ManyToMany` instead of `@manyToMany`
9) `@BelongsToMorphed` instead of `@belongsToMorphed`
10) `@MorphedHasMany` instead of `@morphedHasMany`
11) `@Inverse` instead of `@inverse`

Reason:

Existing popular solutions codestyle.

- Doctrine: https://www.doctrine-project.org/projects/doctrine-annotations/en/latest/index.html
- Phalcon: https://docs.phalconphp.com/3.4/en/annotations

**Comment by wolfy-j** [comment]
Though, lower case approach used in phpDoc (everywhere) and PHPUnit.

**Comment by SerafimArts** [comment]
In "real world" annotations are class objects:
```php
class Example 
{
    public $some = 23;
}

// ...

/**
 * @Example(some = 23)
 */
class Some {}
```

Therefore, it is strange to call them in small letters.

But... However, since the implementation from cycle is incompatible with existing PHP solutions from Phalcon and Doctrine, and also does not correspond to similar solutions in Java, C#, VB and others, I don’t think this is critical.

That's why I created issue instead of pull request.
